version: '3.8'
services:
  devcontainer:
    build:
      dockerfile: ./.devcontainer/Dockerfile
      context: ..
    image: learning-python:latest
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
#     network_mode: service:db
    
#   db:
#     image: postgres:latest
#     restart: unless-stopped
#     volumes:
#       - postgres-data:/var/lib/postgresql/data
#     environment:
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_USER: postgres
#       POSTGRES_DB: postgres

# volumes:
#   postgres-data: